version: 2
jobs:
  build:
    working_directory: ~/docker-hunspell-bdict-wasm
    docker:
      - image: buildpack-deps:trusty
    environment:
      - emscripten_base: "ojkwon/hunspell-bdict-wasm:fb98cae"
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Update submodules
          command: git submodule update --init --recursive --remote
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Prepare docker images for emscripten
          command: |
            docker pull $emscripten_base
            docker run --name hunspell-bdict-wasm-$CIRCLE_BUILD_NUM -t $emscripten_base -w="/hunspell"
            docker cp ./hunspell hunspell-bdict-wasm-$CIRCLE_BUILD_NUM:/hunspell
            docker cp build.sh hunspell-bdict-wasm-$CIRCLE_BUILD_NUM:/hunspell
            docker cp preprocessor.js hunspell-bdict-wasm-$CIRCLE_BUILD_NUM:/hunspell
            docker exec hunspell-bdict-wasm-$CIRCLE_BUILD_NUM "ls -al"
      - run:
          name: Build wasm
          command: |
            # Build docker image, specify commit sha of hunspell
            docker build --build-arg BUILD_SHA=e86aab1345872d7de469a3ebaa294241f8de8a50 -t hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM .
            # Run built docker image, specify container name same as image name
            docker run --name hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM -t hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM
      - run:
          name: Copy artifacts
          command: |
            ARTIFACT_DIR=~/docker-hunspell-bdict-wasm/artifacts
            docker cp hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM:/out $ARTIFACT_DIR
            # File copied from docker container has root access only, modify permission
            sudo chmod -R go+wr artifacts
            # Generate archive for convinience
            tar -zcvf ./hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM.tar.gz artifacts
            cp *.tar.gz $ARTIFACT_DIR
      - store_artifacts:
          path: ~/docker-hunspell-bdict-wasm/artifacts