# Default configuration shared between jobs
defaults: &defaults
  working_directory: ~/docker-hunspell-wasm
  docker:
  - image: circleci/golang:1.10.3-stretch-browsers

version: 2
jobs:
  # Jobs for building wasm binary for hunspell
  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Init submodules
          command: |
             git submodule update --init --recursive
             # generate build artifact folder
             mkdir -p ~/build
      - run:
          name: Build wasm hunspell 1.6.1
          command: |
            BRANCH=v1.6.1
            TARGET=wasm
            # Build docker image, specify commit sha of hunspell
            docker build -t hunspell-dict-wasm_0.1.$CIRCLE_BUILD_NUM --build-arg BRANCH=$BRANCH --build-arg TARGET=$TARGET .
            # Run built docker image, specify container name same as image name
            docker run --name hunspell-dict-wasm_0.1.$CIRCLE_BUILD_NUM -t hunspell-dict-wasm_0.1.$CIRCLE_BUILD_NUM /bin/bash -l -c "./build.sh -o /out/hunspell.js -s WASM=1"
            # Copy build output
            docker cp hunspell-dict-wasm_0.1.$CIRCLE_BUILD_NUM:/out ~/build
      - run:
          working_directory: ~/build
          name: Copy artifacts
          command: |
            # File copied from docker container has root access only, modify permission
            sudo chmod -R go+wr ~/build
            # Generate hash
            sha512sum ./out/hunspell.js > ./out/hunspell.js.sha512
            # Generate archive for convinience
            tar -zcvf ./hunspell-asm-$(echo $CIRCLE_SHA1 | cut -c -7).tar.gz out
            # Flatten file out path
            mv ./out/* ./ && rm -rf ./out
      # Upload artifact into CircleCi artifacts
      - store_artifacts:
          path: ~/build
          destination: build
      # Persist build results to share between different jobs
      - persist_to_workspace:
          root: ~/build
          paths:
            - ./*

  # Jobs to create github release for tagged build
  release:
    <<: *defaults
    steps:
      # Acquire persisted build results
      - attach_workspace:
          at: ~/build
      - run:
          name: Create Release
          command: |
            go get github.com/tcnksm/ghr
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG ~/build

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          # Filter jobs to run on tag only
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build
